title: Genesis' Blog
description: > # this means to ignore newlines until "baseurl:"
  Um blog sobre ciência, o mundo e seus dados.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gallileugenesis.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Gallileu Genesis'
  last_name: ''
  #cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  gallileugenesis  
  email: galileugenesis@gmail.com
  #vk_id: id201664979
  #telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


